# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  identifier = "home"
  weight = 10
  hasChildren = true

[[ main ]]
  name = "Welcome"
  parent = "home"
  url = "/"
  weight = 10

# [[ main ]]
#   name = "About Us"
#   parent = "home"
#   url = "/mission/"
#   weight = 20

# [[ main ]]
#   name = "Social Media"
#   parent = "home"
#   url = "/social-media/"
#   weight = 40

[[ main ]]
  name = "Programs"
  parent = "home"
  url = "/programs/"
  weight = 20

[[ main ]]
  name = "Resume Bank"
  parent = "home"
  url = "https://forms.gle/UkHxwfayCCZ7qGYG8"
  weight = 30

# [[main]]
#   name = "Posts"
#   url = "#posts"
#   weight = 20

# [[main]]
#   name = "Projects"
#   url = "#projects"
#   weight = 30

# [[main]]
#   name = "Publications"
#   url = "#featured"
#   weight = 40
# [[main]]
#   name = "GBM"
#   url = "/gbm"
#   weight = 20

# [[main]]
#   name = "Calendar"
#   url = "/calendar"
#   weight = 25

[[main]]
  name = "Team"
  url = "/e-board"
  weight = 30

# [[main]]
#   name = "SIGs"
#   url = "#sig"
#   weight = 40
# [[main]]
#   name = "Online Store"
#   url = "https://ucfacmw.org/online-store"
#   weight = 50


[[main]]
  name = "Contact"
  url = "/contact"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
