[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.70.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[headers]]
  for = "*.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=UTF-8"

[[headers]]
  for = "index.xml"
  [headers.values]
    Content-Type = "application/rss+xml"

# ===================================================================
# ================== DO NOT TOUCH ANYTHING ABOVE ====================
# ===================================================================

# Here's where you'll add redirect links for the website! :)

# Social Media Redirects
[[ redirects ]]
  from = "/github"
  to = "https://github.com/ucfacmw"
  status = 301

[[ redirects ]]
  from = "/facebook-page"
  to = "https://facebook.com/ucfacmw"
  status = 301

[[ redirects ]]
  from = "/instagram"
  to = "https://www.instagram.com/ucfacmw"
  status = 301

[[ redirects ]]
  from = "/discord"
  to = "https://discord.gg/7QHunCM"
  status = 301
  
[[ redirects ]]
  from = "/sigact/discord"
  to = "https://discord.gg/67pG49uV4Q"
  status = 301
  
[[ redirects ]]
  from = "/twitter"
  to = "https://twitter.com/ucfacmw"
  status = 301

[[ redirects ]]
  from = "/reddit"
  to = "https://www.reddit.com/user/ucfacmw"
  status = 301

[[ redirects ]]
  from = "/home"
  to = "https://ucfacmw.org"
  status = 301
# ===================================================================

# Sign In & Sign Up Redirects
[[ redirects ]]
  from = "/sign-up"
  to = "https://forms.gle/n2TrWn1uk4xJZTar8"
  status = 301

[[ redirects ]]
  from = "/sign-in"
  to = "https://forms.gle/kD26DShoFjd3AEQF9"
  status = 301
# ===================================================================

# Sponsorship Deck Redirect
[[ redirects ]]
  from = "/sponsorship-presentation"
  to = "https://www.canva.com/design/DAECeVTixdw/x3ZImmDh5_0rKbJ0QcaZfA/view?website#2"
  status = 301
# ===================================================================

# Online Store Redirect - Currently INACTIVE
[[ redirects ]]
  from = "/online-store"
  to = "https://ucfacmw.square.site/"
  status = 301
# ===================================================================

# Member Perks Redirects
[[ redirects ]]
  from = "/resume-bank"
  to = "https://forms.gle/UkHxwfayCCZ7qGYG8"
  status = 301

[[ redirects ]]
  from = "/subscribe-newsletter"
  to = "http://eepurl.com/dlb8rD"
  status = 301
  
[[ redirects ]]
  from = "/packages"
  to = "https://forms.gle/z7At65gc51Y3JZeU9"
  status = 301

[[ redirects ]]
  from = "/recognition"
  to = "https://forms.gle/Vc5tzCk2ia8LUUnq6"
  status = 301
  
[[ redirects ]]
  from = "/library-catalog"
  to = "https://drive.google.com/file/d/1zHJwIM-tADmKka-pWVGplcFNBHnFAAvU/view?usp=sharing"
  status = 301
  
[[ redirects ]]
  from = "/forms/library-access"
  to = "https://forms.gle/GVJftCHdV6Fawmot9"
  status = 301
  
[[ redirects ]]
  from = "/library"
  to = "https://drive.google.com/drive/folders/1kAnhTuDJSoqLVcyzZCnJeDjcReYk3kJn?usp=sharing"
  status = 301

# ===================================================================

# Fall 2020 - Sponsor/RSO Collab. Form
[[ redirects ]]
  from = "/event-interest"
  to = "https://forms.gle/xMAd1MTPutFP7r6v7"
  status = 301
# ===================================================================

# Interest Meeting Redirect

# This needs to be changed to fa20-interest-meeting
[[ redirects ]]
  from = "/interest-meeting"
  to = "https://youtu.be/5Xvu8LUmhv0"
  status = 301
  
[[ redirects ]]
  from = "/zoom/interest-meeting"
  to = "https://ucf.zoom.us/j/97905924733"
  status = 301
# ===================================================================

# Zoom links
[[ redirects ]]
  from = "/zoom/gbm"
  to = "https://ucf.zoom.us/j/91996682446"
  status = 301

[[ redirects ]]
  from = "/zoom/workshops"
  to = "https://ucf.zoom.us/j/92264317149"
  status = 301

[[ redirects ]]
  from = "/zoom/acmw-events"
  to = "https://ucf.zoom.us/j/95404856657"
  status = 301

[[ redirects ]]
  from = "/zoom/projects"
  to = "https://ucf.zoom.us/j/97895446265"
  status = 301
  
[[ redirects ]]
  from = "/zoom/dev"
  to = "https://ucf.zoom.us/j/94524431420"
  status = 301

[[ redirects ]]
  from = "/zoom/game-knights"
  to = "https://ucf.zoom.us/j/94208185357"
  status = 301
  
[[ redirects ]]
  from = "/zoom/sigact"
  to = "https://ucf.zoom.us/j/97218838167"
  status = 301
# ===================================================================

# Committee Links
[[ redirects ]]
  from = "/forms/mentee"
  to = "https://forms.gle/kYDtzyY2tnCB3rNd7"
  status = 301

[[ redirects ]]
  from = "/forms/mentor"
  to = "https://forms.gle/vVUD3waBKkSmswhN8"
  status = 301
  
[[ redirects ]]
  from = "/projects-interest"
  to = "https://forms.gle/krnP2kuqXPNcEAiw8"
  status = 301

[[ redirects ]]
  from = "/forms/project-pitches"
  to = "https://docs.google.com/forms/d/e/1FAIpQLSdaiY9r-PBsjdlZsOhYj5W_hgT4rU5KzGtVOLh_YD-z2EX9rA/viewform?usp=sf_link"
  status = 301

[[ redirects ]]
  from = "/contact/mentor-mentee"
  to = "https://docs.google.com/spreadsheets/d/15MEWmHK-0zrUmwrk_bNuqHy5Xw86PKiNiXdRmejWnm4/edit?usp=sharing"
  status = 301

[[ redirects ]]
  from = "/join-committee"
  to = "https://forms.gle/2bQZt5AepzvT1Rvt5"
  status = 301

[[ redirects ]]
  from = "/dev-interest"
  to = "https://forms.gle/ZXrDgdDKnCJWgwTY6"
  status = 301

[[ redirects ]]
  from = "/GitHub-workshop"
  to = "https://forms.gle/HeA7igAU4mvxiumq5"
  status = 301
  
[[ redirects ]]
  from = "/spending-survey"
  to = "https://forms.gle/f7SXKMJwdvoHaASi6"
  status = 301
  
# ===================================================================

# Classmate Matcher Form
[[ redirects ]]
  from = "/find-classmates"
  to = "https://forms.gle/pQ8VoeirpZLYvL3s7"
  status = 301
# ===================================================================

# Linktree redirect
[[ redirects ]]
  from = "/linktree"
  to = "https://linktr.ee/UCFacmw"
  status = 301
# ===================================================================


